// GENERATED by scripts/build-registry.ts — do not edit.
/* eslint-disable */
import type { ToolMeta } from '@rareshape/schema'
import type { ToolModuleLoaders } from '@rareshape/schema'

export const registry: ToolMeta[] = [

] as ToolMeta[]

export const harness: ToolMeta[] = [
  {"slug":"_harness-svg","name":"Harness SVG","tagline":"Every param type, once, in vector.","category":"Shapes","engine":"svg","outputs":["SVG","PNG","GIF","MP4","HTML"],"added":"2026-08-19","animated":true,"duration":4,"fps":60,"aspect":"1:1","keywords":["harness","fixture","test"]},
] as ToolMeta[]

/** Dynamic so that no renderer — and no Three.js — reaches the index bundle. */
export const loaders: ToolModuleLoaders = {
  "_harness-svg": {
    tool: () => import('@/tools/_harness-svg/tool'),
    render: () => import('@/tools/_harness-svg/render'),
  },
}
