import Link from 'next/link'
import type { ToolMeta } from '@rareshape/schema'
import { shortDate } from '@/lib/registry'

/**
 * One cell of the index. The metadata line above the preview does real work —
 * date, category, exports — rather than decorating.
 * The preview itself is generated by the tool through the real export pipeline
 * (see scripts/build-previews.ts); nothing here is hand-made artwork.
 */
export function ToolCard({ tool, index = 0 }: { tool: ToolMeta; index?: number }) {
  return (
    <Link
      href={`/tools/${tool.slug}`}
      style={{ '--i': index } as React.CSSProperties}
      className="group block focus-visible:outline-1"
      data-slug={tool.slug}
      data-category={tool.category}
      data-outputs={tool.outputs.join(' ')}
      data-search={`${tool.name} ${tool.category} ${tool.tagline} ${(tool.keywords ?? []).join(' ')}`.toLowerCase()}
    >
      <div className="flex items-baseline gap-3 mb-2">
        <span className="meta tabular-nums">{shortDate(tool.added)}</span>
        <span className="text-[var(--text-md)] text-[var(--text)] group-hover:underline underline-offset-4 decoration-[var(--faint)]">
          {tool.name}
        </span>
      </div>
      <div className="meta mb-2 truncate">
        {tool.category} <span className="text-[var(--faint)]">—</span> {tool.outputs.join(' ')}
      </div>
      <Preview tool={tool} />
    </Link>
  )
}

function Preview({ tool }: { tool: ToolMeta }) {
  return (
    <div className="rule border bg-[var(--surface)] aspect-[4/3] overflow-hidden relative">
      <div
        className="absolute inset-0 grid place-items-center meta text-[var(--faint)]"
        aria-hidden="true"
      >
        {tool.slug}
      </div>
    </div>
  )
}
