/**
 * Scans /tools and emits registry.generated.ts.
 *
 * The registry is metadata only — serialised as literals, with no import of any
 * tool module. That is what keeps the index bundle free of renderers (and of
 * Three.js). Renderers are reached through the loader map, which is dynamic.
 *
 * Folders prefixed with `_` are harness tools: they get a page and a loader but
 * never appear on the index.
 */
import { readdirSync, statSync, writeFileSync, existsSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

const ROOT = resolve(import.meta.dirname, '..')
const TOOLS_DIR = join(ROOT, 'tools')

export interface ScannedTool {
  slug: string
  dir: string
  harness: boolean
  meta: Record<string, unknown>
}

export async function scanTools(): Promise<ScannedTool[]> {
  if (!existsSync(TOOLS_DIR)) return []
  const found: ScannedTool[] = []

  for (const entry of readdirSync(TOOLS_DIR).sort()) {
    const dir = join(TOOLS_DIR, entry)
    if (!statSync(dir).isDirectory()) continue
    if (entry.startsWith('.')) continue

    const toolFile = join(dir, 'tool.ts')
    if (!existsSync(toolFile)) {
      console.warn(`registry: skipping tools/${entry} — no tool.ts`)
      continue
    }

    const mod = (await import(pathToFileURL(toolFile).href)) as { tool?: { meta?: unknown } }
    const meta = mod.tool?.meta
    if (!meta || typeof meta !== 'object') {
      throw new Error(`tools/${entry}/tool.ts must export \`tool\` from defineTool()`)
    }

    const slug = (meta as { slug?: string }).slug
    if (slug !== entry) {
      throw new Error(`tools/${entry}: slug "${slug}" must match the folder name`)
    }

    found.push({ slug: entry, dir, harness: entry.startsWith('_'), meta: meta as Record<string, unknown> })
  }

  return found
}

function serialise(tools: ScannedTool[]): string {
  return `[\n${tools.map((t) => `  ${JSON.stringify(t.meta)},`).join('\n')}\n]`
}

export async function buildRegistry(): Promise<ScannedTool[]> {
  const tools = await scanTools()
  const listed = tools.filter((t) => !t.harness)
  const harness = tools.filter((t) => t.harness)

  const loaders = tools
    .map(
      (t) =>
        `  ${JSON.stringify(t.slug)}: {\n` +
        `    tool: () => import('@/tools/${t.slug}/tool'),\n` +
        `    render: () => import('@/tools/${t.slug}/render'),\n` +
        `  },`,
    )
    .join('\n')

  const out = `// GENERATED by scripts/build-registry.ts — do not edit.
/* eslint-disable */
import type { ToolMeta } from '@rareshape/schema'
import type { ToolModuleLoaders } from '@rareshape/schema'

export const registry: ToolMeta[] = ${serialise(listed)} as ToolMeta[]

export const harness: ToolMeta[] = ${serialise(harness)} as ToolMeta[]

/** Dynamic so that no renderer — and no Three.js — reaches the index bundle. */
export const loaders: ToolModuleLoaders = {
${loaders}
}
`

  writeFileSync(join(ROOT, 'registry.generated.ts'), out)
  console.log(`registry: ${listed.length} tool(s), ${harness.length} harness`)
  return tools
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  buildRegistry().catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
