/**
 * Builds one self-contained ES module per tool: the tool's `tool.ts`, its
 * `render.ts`, the vanilla eject shell and everything they import, bundled but
 * NOT minified — an ejected file should be readable source.
 *
 * The result is served from /eject/<slug>.js and inlined into the standalone
 * HTML at export time. Three.js is left external and reached through an import
 * map, so a WebGL tool's ejected file stays a few dozen KB instead of a MB.
 */
import { build } from 'esbuild'
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { scanTools } from './build-registry'

const ROOT = resolve(import.meta.dirname, '..')
const OUT_DIR = join(ROOT, 'public', 'eject')
const TEMP_DIR = join(ROOT, '.eject-entries')

export const THREE_VERSION = '0.185.1'
export const THREE_CDN = `https://esm.sh/three@${THREE_VERSION}`

export async function buildEjectBundles(): Promise<string[]> {
  const tools = await scanTools()
  mkdirSync(OUT_DIR, { recursive: true })
  mkdirSync(TEMP_DIR, { recursive: true })

  const built: string[] = []

  try {
    for (const tool of tools) {
      const entry = join(TEMP_DIR, `${tool.slug}.ts`)
      writeFileSync(
        entry,
        `import { tool } from '${toImport(join(tool.dir, 'tool'))}'\n` +
          `import * as render from '${toImport(join(tool.dir, 'render'))}'\n` +
          `import { mount } from '@rareshape/eject'\n\n` +
          `// The params the file was exported with, written into the HTML.\n` +
          `const node = document.getElementById('rs-params')\n` +
          `const params = node ? JSON.parse(node.textContent || '{}') : {}\n` +
          `const source = document.documentElement.dataset.source\n` +
          `const aspect = document.documentElement.dataset.aspect\n\n` +
          `mount({ tool, module: render, params, source, aspect })\n`,
        'utf8',
      )

      const outfile = join(OUT_DIR, `${tool.slug}.js`)
      await build({
        entryPoints: [entry],
        outfile,
        bundle: true,
        format: 'esm',
        target: 'es2022',
        platform: 'browser',
        minify: false,
        keepNames: true,
        legalComments: 'none',
        // Reached through the import map instead of being inlined.
        external: ['three'],
        banner: {
          js:
            `// ${tool.slug} — standalone build.\n` +
            `// Generated by scripts/build-eject.ts. Readable on purpose: this is\n` +
            `// the same render function and param schema the site runs.\n`,
        },
      })

      built.push(outfile)
      console.log(`eject: ${tool.slug}`)
    }
  } finally {
    rmSync(TEMP_DIR, { recursive: true, force: true })
  }

  return built
}

const toImport = (path: string) => path.split('\\').join('/')

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  buildEjectBundles().catch((error) => {
    console.error(error)
    process.exit(1)
  })
}
