/**
 * Every image on the index is generated by the tool it represents, through the
 * real export pipeline. Nothing here is hand-made artwork.
 *
 * For each tool: poster.png (1600×1200), preview.mp4 (3s loop, ≤600KB) and
 * og.png (1200×630, cropped from the poster).
 *
 * Requires a build first — it drives the built site's /lab page in headless
 * Chromium, so previews come out of exactly the code users run.
 */
import { mkdirSync, statSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { openLab, type LabSession } from './lib/lab'

const ROOT = resolve(import.meta.dirname, '..')
const OUT_DIR = join(ROOT, 'public', 'previews')

const POSTER = { width: 1600, height: 1200 }
const OG = { width: 1200, height: 630 }
// What the grid actually loads. A hundred 1600px posters on one page is a
// megabyte per row; the poster stays the full-resolution asset behind it.
const THUMB = { width: 800, height: 600, quality: 0.86 }
const PREVIEW = { width: 640, height: 480, duration: 3, fps: 24, maxBytes: 600 * 1024 }

export async function buildPreviews(only?: string[]): Promise<void> {
  const lab: LabSession = await openLab()

  try {
    const h264 = await lab.page.evaluate(() => window.rareshapeLab!.mp4Supported())
    if (!h264) {
      console.warn(
        'previews: this browser has no H.264 encoder, falling back to an open codec in the MP4 container.\n' +
          '          Run in a Chromium with proprietary codecs (or Chrome) for previews everyone can play.',
      )
    }

    const tools = lab.tools.filter((tool) => (only?.length ? only.includes(tool.slug) : true))

    for (const tool of tools) {
      const dir = join(OUT_DIR, tool.slug)
      mkdirSync(dir, { recursive: true })

      // Poster: the tool's default state at t=0 — the frame that also becomes
      // the OG image, so a tool's defaults have to look good cold.
      const poster = await lab.export({
        slug: tool.slug,
        format: 'png',
        width: POSTER.width,
        height: POSTER.height,
        scale: 1,
        t: 0,
        // No background override: the poster shows the tool's own ground,
        // the same as an export a person would take.
      })
      writeFileSync(join(dir, 'poster.png'), poster.bytes)

      const og = await lab.crop({
        base64: poster.bytes.toString('base64'),
        width: OG.width,
        height: OG.height,
      })
      writeFileSync(join(dir, 'og.png'), og)

      const thumb = await lab.crop({
        base64: poster.bytes.toString('base64'),
        width: THUMB.width,
        height: THUMB.height,
        type: 'image/jpeg',
        quality: THUMB.quality,
      })
      writeFileSync(join(dir, 'thumb.jpg'), thumb)

      let previewNote = 'static'
      if (tool.animated) {
        const bytes = await encodeWithinBudget(lab, tool.slug, !h264)
        writeFileSync(join(dir, 'preview.mp4'), bytes)
        previewNote = `${Math.round(bytes.length / 1024)}KB`
      }

      console.log(
        `previews: ${tool.slug} — poster ${Math.round(poster.size / 1024)}KB, ` +
          `thumb ${Math.round(thumb.length / 1024)}KB, preview ${previewNote}`,
      )
    }
  } finally {
    await lab.close()
  }
}

/**
 * The 600KB budget is a hard ceiling: a hundred of these are on one page.
 * Bitrate is stepped down until the file fits rather than guessed once.
 */
async function encodeWithinBudget(
  lab: LabSession,
  slug: string,
  allowFallbackCodec: boolean,
): Promise<Buffer> {
  let bitrate = 1_400_000
  let last: Buffer | null = null

  for (let attempt = 0; attempt < 4; attempt++) {
    const result = await lab.export({
      slug,
      format: 'mp4',
      width: PREVIEW.width,
      height: PREVIEW.height,
      scale: 1,
      duration: PREVIEW.duration,
      fps: PREVIEW.fps,
      bitrate,
      allowFallbackCodec,
    })
    last = result.bytes
    if (result.bytes.length <= PREVIEW.maxBytes) return result.bytes
    bitrate = Math.round(bitrate * 0.6)
  }

  console.warn(`previews: ${slug} still over budget at ${last?.length ?? 0} bytes`)
  return last as Buffer
}

export function previewExists(slug: string): boolean {
  try {
    return statSync(join(OUT_DIR, slug, 'poster.png')).size > 0
  } catch {
    return false
  }
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  buildPreviews(process.argv.slice(2)).catch((error) => {
    console.error(error)
    process.exit(1)
  })
}
